seed: 2
cuda: 0 # use_gpu
env:
  env_type: gridworld
  env_name: MiniGrid-LavaCrossingS15N10-v0
  obseravibility: image_partial
  num_eval_tasks: 40

train:
  # sample complexity: BAMDP horizon * (num_init_rollouts_pool * num_train_tasks
    #  + num_iters * num_tasks_sample * num_rollouts_per_iter)
    # original 4k iters -> 12M steps
    # 1.5k iters -> 4.55M steps (17 gpu hrs, 31 cpu hrs)
  # original rl training steps: num_iters * updates_per_iter = 1.5M
    # now makes it same as env steps
  num_iters: 300 # number meta-training iterates
  num_init_rollouts_pool: 30 # 80 #  before training
  num_rollouts_per_iter: 5  # 1 #
  buffer_size: 1e6 # or 1e6? old belief

  num_updates_per_iter: 500
  batch_size: 256 # to tune based on sampled_seq_len

eval:
  log_interval: 5 # 10 num of iters
  save_interval: 1 # -1
  log_tensorboard: true

policy:
  seq_model: mlp
  algo_name: sacd # [td3, sac]
  teacher_dir: /data/pulkitag/models/idanshen/pomdp-baselines/gridworld/MiniGrid/LavaGapS7/Markovian_sacd/alpha-0.1/gamma-0.9/New_Expert/

  dqn_layers: [128, 128]
  policy_layers: [128, 128]
  lr: 0.0003
  gamma: 0.9
  tau: 0.005

  observ_embedding_size: 0 # use image encoder instead
  image_encoder:
    from_flattened: False

  sacd:
    entropy_alpha: 0.1
    automatic_entropy_tuning: True
    target_entropy: 0.4 # the ratio: target_entropy = ratio * log(|A|)
    alpha_lr: 0.0003

  eaacd:
    initial_coefficient: 5.0
    coefficient_tuning: Fixed # Can be Fixed, Target, EIPO, ADVISOR
    target_coefficient: 1.0 # Relevant for 'Target' coefficient tuning
    coefficient_lr: 0.0003
    split_q: True

  DAgger:
    loss_type: CE