seed: 1
cuda: 0 # use_gpu
env:
  env_type: mujoco
  env_name: HandManipulatePen_ContinuousTouchSensors-v1
  obseravibility: partial
  num_eval_tasks: 1000
  num_train_envs: 60

train:
  # original rl training steps: num_iters * updates_per_iter = 1.5M
    # now makes it same as env steps
  num_iters: 100000 # 38000 # number meta-training iterates
  num_init_rollouts_pool: 100 # 80 #  before training
  num_rollouts_per_iter: 10  # 1 #
  buffer_size: 4e6 # or 1e6? old belief

  num_updates_per_iter: 1000
  batch_size: 128 # to tune based on sampled_seq_len
  sampled_seq_len: 30 # -1 is all, or positive integer
  sample_weight_baseline: 0.0
  data_collection_method: both
  epsilon: 0.1
  HER: False

eval:
  log_interval: 30 # 10 num of iters
  save_interval: 1 # -1
  log_tensorboard: true

policy:
  separate: True
  seq_model: lstm # [lstm, gru]
  algo_name: elfc # [td3, sac,eaacd]
#  teacher_dir: /home/idanshen/pomdp-baselines/mujoco/HandManipulatePen_ContinuousTouchSensors-v1/Markovian_sac/alpha-0.01/gamma-0.9/01-11:18-21:17.66/
  teacher_dir: /data/pulkitag/models/idanshen/pomdp-baselines/mujoco/HandManipulatePen_ContinuousTouchSensors-v1/Markovian_sac/alpha-0.01/gamma-0.9/01-13:23-24:22.62/

  action_embedding_size: 16
  observ_embedding_size: 128
  reward_embedding_size: 0
  rnn_hidden_size: 128

  dqn_layers: [512, 256, 128]
  policy_layers: [512, 256, 128]
  lr: 0.0003
  gamma: 0.9
  tau: 0.005

  sac:
    entropy_alpha: 0.01
    automatic_entropy_tuning: True
#    target_entropy: None # the ratio: target_entropy = ratio * log(|A|)
    alpha_lr: 0.0003

  eaac:
    initial_coefficient: 0.3
    coefficient_tuning: Fixed # Can be Fixed, Target, EIPO
    target_coefficient: 1.0 # Relevant for 'Target' coefficient tuning
    coefficient_lr: 0.0003
    split_q: True
    min_coefficient: 0.01
    max_coefficient: 3.0

  DAggerc:
    loss_type: L2

  elfc:
    min_v: 10000
    imitation_policy_dir: /home/idanshen/pomdp-baselines/mujoco/HandManipulatePen_ContinuousTouchSensors-v1/Markovian_DAggerc/gamma-0.9/03-16:15-00:26.98/

  advisorc:
    temprature: 0.25